<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="tests" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.001978">
    <testsuite name="tests\ConfigLogicTest" file="/Users/git/component_tp5/tests/ConfigLogicTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.001978">
      <testcase name="testQuery" class="tests\ConfigLogicTest" classname="tests.ConfigLogicTest" file="/Users/git/component_tp5/tests/ConfigLogicTest.php" line="50" assertions="0" time="0.001978">
        <error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
        <system-out>string(2) "id"
array(1) {
  ["create_time"]=&gt;
  string(4) "desc"
}
array(2) {
  [0]=&gt;
  string(2) "id"
  [1]=&gt;
  array(1) {
    ["create_time"]=&gt;
    string(4) "desc"
  }
}
</system-out>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
